name: Update Signapk Submodule Pointer

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: false

      - name: Set Git identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Sync submodule
        run: git submodule sync --recursive

      - name: Initialize submodule
        run: git submodule update --init --force --recursive external/apktool

      - name: Checkout desired commit
        run: |
          cd external/signapk
          git fetch origin
          git checkout b85014d95bc87c82fa4f2c79bc43165e6ea8565f
          cd ..

      - name: Commit updated pointer
        run: |
          git add external/signapk
          git commit -m "external: signapk: update signapk to b85014d"
          git push origin sixteen
